name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:  # 允许手动触发

env:
  CRATE_NAME: mdbook-epub

jobs:
  release:
    name: Build release binary
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: aarch64-apple-darwin

      - name: Build release
        run: cargo build --release --target aarch64-apple-darwin

      - name: Prepare artifact
        run: |
          mkdir -p target/stage
          cd target/aarch64-apple-darwin/release
          tar czvf ../../stage/${{ env.CRATE_NAME }}-aarch64-apple-darwin.tar.gz ${{ env.CRATE_NAME }}
          cd -

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/stage/${{ env.CRATE_NAME }}-aarch64-apple-darwin.tar.gz
          asset_name: ${{ env.CRATE_NAME }}-aarch64-apple-darwin.tar.gz
          tag: ${{ github.ref }}
