name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:  # Added manual trigger support

jobs:build:
    runs-on: macos-latest
    env:
      EPUBCHECK_PATH: epubcheck

    steps:
      - name: Set up Rust
        uses: actions/checkout@v4

      - name: Install cargo version
        uses: dtolnay/rust-toolchain@stablewith:
          targets: aarch64-apple-darwin  # Specify Apple Silicon target

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install epubcheck
        run: brew install epubcheck
        shell: bash

      - name: Install cargo auditrun: cargo install cargo-audit

      - name: Show rust version
        run: cargo --version- name: Build
        run: cargo build --release --verbose --target aarch64-apple-darwin

      - name: Run tests
        run: cargo test --verbose --target aarch64-apple-darwin -- --include-ignored
        env:
          EPUBCHECK_JAR: ${{ env.EPUBCHECK_JAR }}

      - name: Run Clippy
        run: cargo clippy --target aarch64-apple-darwin -- --no-deps -Dwarnings

      - name: Audit
        run: cargo audit
        
      # New step to upload the compiled binary- name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mdbook-epub-aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/mdbook-epub
          overwrite: true
